AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - Guardfile
    - spec/**/*_spec.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
